const mongoose=require('mongoose');
const productSchema=new mongoose.Schema({
    id:{
        type:String,
    },
    product_name:{
        type:String,
        required:true,
    },
    product_image:{
      type:Array,
      required:true
    },
    product_cost:{
        type:Number,
        required:true
      },
      product_desc:{
        type:String,
        required:true
      },
      product_stock:{
        type:String,
        required:true
      },
      product_rating:{
        type:String,
        required:true
      },
      product_dimension:{
        type:String,
        required:true
      },
      product_material:{
        type:String,
        required:true
      },
      color_id:{
         type:mongoose.Schema.Types.ObjectId,
         ref:"color"
      },
      category_id:{
         type:mongoose.Schema.Types.ObjectId,
         ref:"category"
      }
})
module.exports=mongoose.model('product',productSchema);