(function(q){var v=window.AmazonUIPageJS||window.P,f=v._namespace||v.attributeErrors,d=f?f("DetailPageTwisterViewAsset",""):v;d.guardFatal?d.guardFatal(q)(d,window):d.execute(function(){q(d,window)})})(function(q,v,f){q.when("A","dp-refresh-handler","view-util","twister-string-constants","dp-interactive-page-refresh-handler","twister-dimension-subview-promise-handler").register("page-refresh-view",function(d,H,h,n,w,x){function t(x,u,k){function t(b){return{chunk:function(c){var b=c.ASIN,m=c.Value;
c=c.FeatureName;if(!l.hiddenFeatures[c]){var a=c,g,e;try{a&&m&&m.content&&(e=m.content[a],"undefined"!==typeof e&&(g=r("#"+a),g.html(e),g.css({opacity:""})))}catch(k){a=a||"NoFeatureName",B.logFatal(k,{message:"Error in feature"+a})}l.twisterRefreshHandler.stampFeature(a,b);"twister-slot-price_feature_div"==c&&(b=m?m.content:null,g=r(".swatchSelect .twisterSwatchPrice").html(),m=r(".swatchSelect .price_slot_ppu").html(),g&&b&&b.priceToSet&&(g=d.trim(g),b.priceToSet!==g&&(r(".swatchSelect .twisterSwatchPrice").html(b.priceToSet),
y("twisterUpdatePriceMismatch"))),m&&b&&b.hasPricePerUnit&&b.pricePerUnitDisplay&&(m=d.trim(m),b.pricePerUnitDisplay!==m&&(r(".swatchSelect .price_slot_ppu").html(b.pricePerUnitDisplay),y("twisterUpdatePricePerUnitMismatch"))))}},success:function(b,p,m){y("twisterUpdateSuccess");w.updateRenderTime()},error:function(b,p,m){Twister.$("#variations-overlay").hide();y("twisterUpdateFailure");Twister.showErrorMessageOnFailure&&(alert(Twister.errorMessageOnFailure),location.reload())},abort:function(b){B.logFatal("Ajax aborted: "+
b)},timeout:4E4}}function D(b,c,p,m,a){var g=[];"parent"===b?(c=C(c,m,"parent",a),g.parent=c,c=C(p,m,"partial",a),g.partial=c):(c=C(p,m,b,a),g[b]=c);return g}function z(b,c,p,m,a){for(var g in b)if(b.hasOwnProperty(g)){if("full"===g){var e=p.dimensionType,k=l.twisterUtil.getDimensionInfo().length,n=p.dimensionDisplayType,h=p.newAsin,w=a&&(d.state("dp-twister-csm")||{}).updateCSMPageTypeId;l.twisterRefreshHandler.startMeasurement(h,e,k,n,w?h:f,w?["is-twister","parentAsin-"+E]:f)}e=b[g].twisterRefreshParams;
k=b[g].notifyClientParams;a&&(r(l.config[g].affectedFeatures).css({opacity:.5}),l.twisterRefreshHandler.doPageRefresh(null,e,c,m));K(k.asin,k.id,g,a)}}function e(){r.each(u.contextMetaData,function(b,c){var p={};c=c.elementList||[];var m=c.length,a=[];p.click={};p.mouseOver={};for(var g=0;g<m;g++){var e=r("#"+c[g].divToUpdate);a.push("#"+c[g].divToUpdate);e.length&&c[g].customClientFunction&&(c[g].updateOnHover&&(p.mouseOver[c[g].divToUpdate]=e.attr("customfunctionname")),p.click[c[g].divToUpdate]=
e.attr("customfunctionname"))}l.config[b].affectedFeatures=a.join(",");l.config[b].clientFeatures=p})}function K(b,c,p,m){var a="",a=m?n.EVENT_TYPE_CLICK:n.EVENT_TYPE_MOUSEOVER;r.each(l.config[p].clientFeatures[a],function(a,m){try{var p=function(){l.twisterRefreshHandler.stampImageLoad(b)};(function(){var a={};a.P=q;(function(){eval("var P \x3d this.P;");eval("0, "+m)(c,DetailPage.StateController,p)}).call(a)})()}catch(e){B.logFatal("Client feature - "+a+", threw and exception :- "+e)}})}function C(b,
c,p,m){var a={},g={};a.asinList=b;a.id="parent"===p?b:"partial"===m?c:b;a.mType=p;a=L(p,a);p=!1;(m=d.state("pwState"))&&(p=m.isTryState);p&&(a.isTryState=p);a=l.twisterRefreshHandler.createCustomParamsMap({},a);g.asin=b;g.id=c;return{twisterRefreshParams:a,notifyClientParams:g}}function L(b,c){r.each(u.contextMetaData[b].mTypeSpecificURLParams,function(b,m){c[b]=m});return c}function M(b){b=l.twisterUtil.getSelectionInfoFromSelectedVariationValuesMap(b.selected_variation_values);l.twisterUtil.isFullySelected(b)?
l.currentPageSelectionState="full":l.currentPageSelectionState="partial"}function N(b){var c={};c.config=b.measurement;c.dimensionDisplayType=b.dimensionsDisplayType;c.storeID=b.storeID;c.productGroupID=b.productGroupID;return c}function O(b){b=b.immutableURLPrefix;var c=null;b&&-1!=b.indexOf("?")&&(b=b.split("?")[1],0<b.length&&(c={},b=b.split("\x26"),d.each(b,function(b){b=b.split("\x3d");c[b[0]]=b[1]})),c.isFlushing=2,c.dpEnvironment=Twister.dpEnvironment);return c}function F(b,c){var e;"partial"===
b&&"partial"===c&&(e="partial");"partial"===b&&"full"===c&&(e="full");"full"===b&&"partial"===c&&(e="parent");"full"===b&&"full"===c&&(e="full");return e}var l=this,E=u.parent_asin,A=v.ue,G="",B=new k("dpTwisterPageRefreshView");this.twisterUtil=x.util;this.twisterFeatureName="Twister";this.currentPageSelectionState;this.twisterRefreshHandler;this.config={partial:{},full:{},parent:{},master:{}};this.hiddenFeatures={intermediateEOS:1,EOS:1};l.viewUtil=new h(x);l.subType;var y=function(b){A&&A.count&&
A.count(b,(A.count(b)||0)+1)};(function(){M(u);e();var b={featureName:l.twisterFeatureName},c=N(u);l.twisterRefreshHandler=new H(b,null,c);b=O(u.twisterUpdateURLInfo);l.twisterRefreshHandler.addParams(b);x.registerPassive({viewAttribution:"DetailPage",viewName:"WebTwisterRefreshView"},{updateView:function(b,c){var a={};if(b!==n.METADATA){var a={},e;e=f;if(c)switch(b){case n.VARIATION_CHANGE:e=c.selected().selInfo;break;case n.VARIATION_PEEK:e=c.peek().selInfo}a.selectionInfo=e;a.dimensionCombination=
l.viewUtil.getCurrDimCombId(a.selectionInfo,"_","X");e=l.twisterUtil.isFullySelected(a.dimensionCombination);a.childAsin=l.twisterUtil.getAsinFromSelectionInfo(a.selectionInfo,e);a.newPageSelectionState=e?"full":"partial";a.mTypeForRefresh=F(l.currentPageSelectionState,a.newPageSelectionState);a.newAsin="parent"===a.mTypeForRefresh?E:a.childAsin;a.doNotAbort="parent"===a.mTypeForRefresh?!0:!1;a.twisterCallListParams=D(a.mTypeForRefresh,a.newAsin,a.childAsin,a.dimensionCombination,a.newPageSelectionState);
a.optionsForTwisterRefresh=t(c);a.pageRefreshMeasure={newAsin:a.newAsin,dimensionType:G,dimensionDisplayType:u.dimensionsDisplayType}}switch(b){case n.VARIATION_CHANGE:l.subType!==n.PRODUCTIZED_VIEW_SUBTYPE&&(z(a.twisterCallListParams,a.optionsForTwisterRefresh,a.pageRefreshMeasure,a.doNotAbort,!0),l.currentPageSelectionState=a.newPageSelectionState,l.subType=f);break;case n.METADATA:switch(c.subType){case n.DP_STATE_VIEW_SUBTYPE:G=c.divMetadata.dimDisplayType;break;case n.PRODUCTIZED_VIEW_SUBTYPE:l.subType=
c.subType,a.dimensionCombination=c.newDimCombID,a.childAsin=c.childAsin,a.newAsin=c.newAsin,a.newPageSelectionState=l.twisterUtil.isFullySelected(a.dimensionCombination)?"full":"partial",a.mTypeForRefresh=F(l.currentPageSelectionState,a.newPageSelectionState),a.doNotAbort="parent"===a.mTypeForRefresh?!0:!1,a.twisterCallListParams=D(a.mTypeForRefresh,a.newAsin,a.childAsin,a.dimensionCombination,a.newPageSelectionState),a.optionsForTwisterRefresh=t(c),a.pageRefreshMeasure={newAsin:a.newAsin,dimensionType:c.divMetaData?
c.divMetaData.dimDisplayType:f,dimensionDisplayType:u.dimensionsDisplayType},z(a.twisterCallListParams,a.optionsForTwisterRefresh,a.pageRefreshMeasure,a.doNotAbort,!0),l.currentPageSelectionState=a.newPageSelectionState}}}})})()}var r=d.$;x.registerDimensionSubView("page-refresh-view",t);return t});q.when("A").register("twister-common-constants",function(d){return{FAMILY_SIZE_BUCKET_LIMITS:[0,3,8,25,50,100,1E3,5E3],DEFAULT_SELECTION_TAG:"defaultSelection",BottomSheet:{TRIGGERING_CRITERION_BOTTOMSHEET_OPEN:"onBottomsheetOpen",
BOTTOM_SHEET_SELECTOR:"#twister_bottom_sheet",OVERFLOW_THRESHOLD:8,BOTTOM_SHEET_INIT_TIME:"dpBottomSheetInitTime",PREFETCH_AJAX_CALLS_COMPLETED_EVENT:"prefetchAjaxCallsCompleted"},SortingFiltering:{PRICE_SORT_TOGGLE_SWITCH_CLICK_ON_METRIC:"DPBottomSheetSortingToggleSwitchClickOn",PRICE_SORT_TOGGLE_SWITCH_CLICK_OFF_METRIC:"DPBottomSheetSortingToggleSwitchClickOff",PRICE_SORT_TOGGLE_SWITCH_ENABLED_STATUS_METRIC:"DPBottomSheetPriceSortingToggleSwitchEnabledStatus",PRIME_FILTER_TOGGLE_SWITCH_CLICK_ON_METRIC:"DPBottomSheetPrimeFilteringToggleSwitchClickOn",
PRIME_FILTER_TOGGLE_SWITCH_CLICK_OFF_METRIC:"DPBottomSheetPrimeFilteringToggleSwitchClickOff",PRIME_FILTER_TOGGLE_SWITCH_ENABLED_STATUS_METRIC:"DPBottomSheetPrimeFilteringToggleSwitchEnabledStatus",SORTING_TYPE_PRICE:"price",SORTING_TYPE_UNSORTED:"unsorted",PREFETCH_AJAX_CALLS_COMPLETED_EVENT:"prefetchAjaxCallsCompleted",TOGGLE_SWITCH_STATE_OFF:"off",TOGGLE_SWITCH_STATE_ON:"on",PRICE_SORTING_ENABLED_PARAMETER:"priceSortingEnabled",PRICE_SORTING_PRIORITY_NAME_PARAMETER:"priceSortingPriorityName",ALTER_TYPE_NAME_PRICE:"price",
ALTER_TYPE_NAME_PRIME:"prime",ALTER_SUB_TYPE_ENABLE:"enable",ALTER_SUB_TYPE_DISABLE:"disable",ALTER_TYPE_SORT:"sort",ALTER_TYPE_FILTER:"filter",PRICE_SORT_TOGGLE_SWITCH_SELECTOR:".priceSortToggleSwitch",PRIME_FILTER_TOGGLE_SWITCH_SELECTOR:".primeFilterToggleSwitch",EXPERIMENT_PRICE_SORTING:"priceSorting",EXPERIMENT_PRIME_FILTERING:"primeFiltering",ATTRIBUTE_PRICE_SORTING_PRIORITY:"priorityName",ATTRIBUTE_SORT_BY_PRICE_STRING:"sortByPriceString",ATTRIBUTE_SORTED_BY_PRICE_STRING:"sortedByPriceString",
ATTRIBUTE_TOOL_NAME:"toolName",TOOL_TYPE_TOGGLE_SWITCH:"toggleSwitch"}}});"use strict";q.when("A","twister-util","ready").execute(function(d,q){var h=v.ue;if(d.state("dimensionKeyList")!==f)for(var n in d.state("dimensionKeyList").dimensionKeys)n!==f&&(d.on("a:popover:beforeShow:mobile-twister_"+n,function(n){d.state("twisterInteractability")===f&&h&&"function"===typeof h.count&&h.count("Twister:blankTwisterSecView",(h.count("Twister:blankTwisterSecView")||0)+1)}),d.on("a:popover:beforeHide:mobile-twister_"+
n,function(d){if(d&&d.popover){d=d.popover.getContent();var n=0<d.find(".aw-twister-row:first").length;d&&!n&&h&&"function"===typeof h.count&&h.count("blankTwisterSecondaryView",(h.count("blankTwisterSecondaryView")||0)+1)}}))});"use strict";q.when("A").register("twister-bottom-sheet-container",function(d){return{getInstance:function(){return this.sheetViewInstance},saveInstance:function(f){this.sheetViewInstance=f;d.trigger("dp:sheet:twister:initialized")}}});"use strict";q.when("A","a-sheet","jQuery",
"ready").execute(function(d,f,h){d.on("a:sheet:afterShow:bottom_sheet_mediaMatrix",function(){var d=h("#mediaMatrix_bottomSheet_view_div").find("#format-picker-scroller"),f=d.find("#selected-format"),q=f.offset().left,t=Math.abs(f.width()),f=Math.max(document.documentElement.clientWidth,v.innerWidth||0),t=f-t,r=d.scrollLeft();(q>t||0>=q)&&d.scrollLeft(r+q-f/3)})});q.when("A","view-util","twister-string-constants").register("hover-refresh-view",function(d,v,h){var n=d.$;return function(w,x,t){function r(){d.each(x.contextMetaData,
function(d,f){var e={};d=d.elementList||[];var h=d.length;e.mouseOver=[];for(var n=0;n<h;n++)d[n].customClientFunction&&d[n].updateOnHover&&e.mouseOver.push(d[n].divToUpdate);k.clientFeatures[f]=e})}function I(f,z){d.each(k.clientFeatures[z][h.EVENT_TYPE_MOUSEOVER],function(e){try{var d=n("#"+e),k;d.length&&(k=d.attr("customfunctionname"),function(){var e={};e.P=q;(function(){eval("var P \x3d this.P;");eval("0, "+k)(f,DetailPage.StateController)}).call(e)}())}catch(h){J.logFatal("Client feature - "+
feature+", threw and exception :- "+h)}})}function u(d){d=k.twisterUtil.getSelectionInfoFromSelectedVariationValuesMap(d.selected_variation_values);k.twisterUtil.isFullySelected(d)?k.currentPageSelectionState="full":k.currentPageSelectionState="partial"}var k=this,J=new t("dpTwisterHoverRefreshView");this.twisterUtil=w.util;this.twisterFeatureName="TwisterHover";this.currentPageSelectionState;this.clientFeatures={partial:{},full:{},parent:{},master:{}};k.viewUtil=new v(w);k.subType=f;(function(){function n(d){d=
k.viewUtil.getCurrDimCombId(d,"_","X");var e=k.twisterUtil.isFullySelected(d)?"full":"partial",f,h=k.currentPageSelectionState;"partial"===h&&"partial"===e&&(f="partial");"partial"===h&&"full"===e&&(f="full");"full"===h&&"partial"===e&&(f="parent");"full"===h&&"full"===e&&(f="full");e=[f];"parent"===f&&(e=["parent","partial"]);return{clientFeatureToRefresh:e,dimensionCombination:d}}u(x);r();w.registerPassive({viewAttribution:"DetailPageTwister",viewName:"WebTwisterHoverRefreshView"},{updateView:function(q,
e){switch(q){case h.VARIATION_PEEK:var r={};q=e.peek().selInfo;r=n(q);d.each(r.clientFeatureToRefresh,function(d){I(r.dimensionCombination,d)});case h.VARIATION_CHANGE:k.subType!==h.PRODUCTIZED_VIEW_SUBTYPE&&(q=e.selected().selInfo,e=k.viewUtil.getCurrDimCombId(q,"_","X"),k.currentPageSelectionState=k.twisterUtil.isFullySelected(e)?"full":"partial",k.subType=f);break;case h.METADATA:switch(e.subType){case h.PRODUCTIZED_VIEW_SUBTYPE:k.subType=e.subType,k.currentPageSelectionState=k.twisterUtil.isFullySelected(e.newDimCombID)?
"full":"partial"}}}})})()}})});